### ISSUE TITLE
Adding Homebridge UI X setting?

### ISSUE THREAD

**Issue by Aekung** [hirakujira/homebridge-ambiclimate-platform#1]
First of all, I would like to say thank youuuuuuuuuu for this plugin! I have been using the Homebridge Ambi Climate and Thermostats for ages and it kinda slow my Homebridge down drastically. I was so sad that both plugin are abandoned. Thanks for reviving the plugin for Ambi Climate once again and this time is even better than what we've got.

Do you also planing to make the plugin verified? Can you please consider adding backend configuration in Homebridge UI for an easy usage? I don't mind having to edit json file myself but it would be very convenient to be able to config it with human language on Homebridge UI.

Anyway, thanks so much for this plugin!

**Comment by Aekung** [comment]
Ohhh, my bad. The UI Config is already there. lollll.

I guess I was too hype seeing plugin for Ambi Climate in 2021 so I jumped in here requesting things to fast lolll.

**Comment by hirakujira** [comment]
Yes it already has UI config. I will try to apply for the verification, thanks for your feedback!
