### ISSUE TITLE
Is anyone experiencing API error?

### ISSUE THREAD

**Issue by Aekung** [hirakujira/homebridge-ambiclimate-platform#10]
It's all just happened today. Out of sudden, Ambiclimate API seems to be offline or changed by Ambi Climate since it's unreachable and starts throwing API Token error in the log.

I checked on Ambi Climate Dev Portal website and found that it's unreachable with 503 error as well. 

Am I the only experiencing this or everyone is having the same problem?

**Comment by hirakujira** [comment]
Same here. error 503 in the console of homebridge.

**Comment by Aekung** [comment]
> Same here. error 503 in the console of homebridge.

At least it’s still good to know that I’m not alone. Will try checking with Ambi Team on application to see if something is wrong with their API server.

**Comment by Aekung** [comment]
The problem seems to be solved. API server is reachable again, at least here on my side.

**Comment by hirakujira** [comment]
It's back up for me too.
