### ISSUE TITLE
I got TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Aekung** [hirakujira/homebridge-ambiclimate-platform#2]
Hi,
It's me again. I have just done installed your plugin and it gives me error on homebridge and also crashes my homebridge. The error said "TypeError: Cannot read property 'value' of undefined". I'm not sure which value is undefined but I think you might be able to help.

**Describe The Bug:**
The "TypeError: Cannot read property 'value' of undefined" error preventing homebridge from restarting.

**To Reproduce:**
Installed the plugin. configured everything up. Restarted the homebridge then the error occurs.

**Expected behavior:**
Homebridge should be able to startup with plugin installed.

**Logs:**

```
[26/01/2021, 10:56:40] TypeError: Cannot read property 'value' of undefined
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/src/airconditionAccessory.ts:75:43
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:2055:17
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at runSingle (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:137:13)
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at flush (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:125:13)
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at processTicksAndRejections (internal/process/task_queues.js:75:11)
Jan 26 10:56:40 raspberrypi homebridge[6597]: [26/01/2021, 10:56:40] TypeError: Cannot read property 'value' of undefined
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/src/airconditionAccessory.ts:85:48
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:2055:17
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at runSingle (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:137:13)
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at Timeout.flush [as _onTimeout] (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/q/q.js:125:13)
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at listOnTimeout (internal/timers.js:554:17)
Jan 26 10:56:40 raspberrypi homebridge[6597]:     at processTimers (internal/timers.js:497:7)
```

**Plugin Config:**

```json
 {
            "clientId": "8c251f40-9cf3-48d4-ad5b-XXXXXXXXXXXXXXX",
            "clientSecret": "acb328de-3c81-427a-XXXXXXXXXXXXXXX",
            "username": "ae.XXXXXXX@gmail.com",
            "password": "XXXXXXXXXXXXXXX",
            "showFeedbacks": true,
            "accessories": [
                {
                    "roomName": "Bedroom",
                    "locationName": "Home"
                },
                {
                    "roomName": "Home-Theater",
                    "locationName": "Home"
                }
            ],
            "platform": "AmbiClimatePlatform"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.0.5
* **Homebridge Version**: 1.3.0-Beta47
* **Node.js Version**: v14.15.4
* **NPM Version**: 6.14.8
* **Operating System**: Raspbian

**Comment by hirakujira** [comment]
Could you please try whether it's cause by multiple devices? Because I only have one device, please test if it works when there's only one device.

**Comment by Aekung** [comment]
Tried with plugin version 1.0.6 but still it doesn't work even with 1 device.

I'm using Ambi Climate 2 and Ambi Climate Mini. Tried on both products one by one and it doesn't work. Hope it could help.

**Comment by hirakujira** [comment]
I add error log to the package. Please install v1.0.7 and paste the error message. It would be something like 'Get current relative humidity failed.'

**Comment by Aekung** [comment]
I did update to v1.0.7 but I'm not sure where would I be able to find the error log since the homebridge log doesn't show anything like "Get current relative humidity failed". What I did is uncommenting "#DEBUG=*" in /etc/default/homebridge. If what I've done is right, then I can't seem to find the error like what you said.

If it's not the right way, please kindly tell me how to so I can do it and inform you the error log.

**Comment by Aekung** [comment]
It seems to me that both the temperature and the humidity don't load up so it crashes the Homebridge. I tried configuring the plugin multiple times and some times it loads up for few minutes showing 0.0 on both temperature and humidity but the power state and fan is displaying correctly. Once I tried to reload the app by switching between room and then switching back again, the homebridge crashes with ambiclimate-platform error I posted above.

Because of this, I believe it's both the temperature and the humidity data that don't feed up correctly.

**Comment by hirakujira** [comment]
I updated the package to v1.0.9, can you try again and check whether it shows detailed error message?

You don't need to change the config of homebridge, it should shows automatically.

**Comment by Aekung** [comment]
Updating now. Will get back to you the soonest.

**Comment by Aekung** [comment]
Here is the error

```
Jan 26 13:35:52 alex-home homebridge[30019]: [26/01/2021, 13:35:52] [AmbiClimatePlatform] Get current relative humidity failed.[object Object]
Jan 26 13:35:52 alex-home homebridge[30019]: [26/01/2021, 13:35:52] [AmbiClimatePlatform] Get current tempature failed.[object Object]
```

It's both Temperature and Humidity as suspected.

Testing this, I disabled Show Feedback and HeaterCooler Mode. And for some reason, version 1.0.9 doesn't crash Homebridge even when the data is not feeding correctly.

Please let me know if I could do anything next in order to help you diagnose the issue.

**Comment by hirakujira** [comment]
Sorry for the inconvenience. Seems that the format is different between your device data and mine. I pushed v1.1.10 for more detailed log. Could you try again?

**Comment by Aekung** [comment]
Of course, I'm doing it right away.

**Comment by Aekung** [comment]
Here is the error produced from v.1.0.10

```
[26/01/2021, 13:46:10] [AmbiClimatePlatform] Get current tempature failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[26/01/2021, 13:46:10] [AmbiClimatePlatform] Get current relative humidity failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[26/01/2021, 13:46:11] [AmbiClimatePlatform] Get current relative humidity failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[26/01/2021, 13:46:11] [AmbiClimatePlatform] Get current tempature failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
```

Hope this helps.

**Comment by hirakujira** [comment]
Huh, this is weird actually. As the log shows, the request is not valid. In general, it caused by your account configs. However, if you can change the status of the device, then your config should be correct...

Did you use the old Ambi Climate homebridge plugin before? Did it work?

**Comment by Aekung** [comment]
I did use the old version before and it works nicely. It's only that Homebridge keeps telling me that the plugin is kinda slow and it slows down the whole homebridge so I wish to switch to a newer one like this.

I did try creating new app in ambiclimate web for new Client ID and Client Secret but it doesn't seem to work as well. Just my 2 cent question though, what you need to do is only to create the new app in Ambi Climate and use the Client ID and Client Secret that ambi gives you, am I right? The quick start has 5 steps but in order to get the Client ID and Client Secret, we just have to do the first step right?

Thank you and looking forward to hearing from you.

**Comment by Aekung** [comment]
Tried to power on and off the Air Conditioner in my room but it doesn't work. Sorry my bad. I thought it works as first dew too what I see as a status in Homekit.

**Comment by hirakujira** [comment]
I just use the same clientID, clientSecret, username and password before. I also tried to create a new app and it still works. And yes, you only need to use the client ID and client secret that ambi gives to you. Also, the callback URL of the application is : https://httpbin.org/get

**Comment by Aekung** [comment]
I reversed back to Homebridge Ambi Climate with the same Client ID and Client Secret still working great. Perhaps you might hardcoded something that is relying on your credential somehow that it rejects my credential once when I try your plugin?

**Comment by hirakujira** [comment]
I didn't hardcode something like that. Is it possible for you to change your account password and provide your account for me to test?

**Comment by Aekung** [comment]
I have sent you and email with my credential (and a password for you). Thank you very much for wanting to look into this.

Please let me know if I can be of any help.

**Comment by hirakujira** [comment]
Thank you so much for your kindly help!
I already fix the bug: it's caused by a silly typo which would break this plugin if you have multiple device registered.

**Comment by Aekung** [comment]
I seem to have new error after updated the plugin to 1.1.0. Here is the error

```
Jan 26 15:28:18 raspberrypi homebridge[13921]: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at validateString (internal/validators.js:124:11)
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at Url.parse (url.js:160:3)
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at Object.urlParse [as parse] (url.js:155:13)
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/node-ambiclimate/ambi-auth.js:114:24
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
Jan 26 15:28:18 raspberrypi homebridge[13921]:   code: 'ERR_INVALID_ARG_TYPE'
Jan 26 15:28:18 raspberrypi homebridge[13921]: }
Jan 26 15:28:18 raspberrypi homebridge[13921]: Access Token Error The "url" argument must be of type string. Received undefined
Jan 26 15:28:18 raspberrypi homebridge[13921]: ReferenceError: nil is not defined
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/node-ambiclimate/ambi-auth.js:135:9
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Jan 26 15:28:18 raspberrypi homebridge[13921]: ReferenceError: nil is not defined
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at /usr/local/lib/node_modules/homebridge-ambiclimate-platform/node_modules/node-ambiclimate/ambi-auth.js:135:9
Jan 26 15:28:18 raspberrypi homebridge[13921]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Note that I'm still using your password to try =)


**UPDATE: My bad. I typed the wrong password. Now that I used the right password, I'm testing it and will come back with the feedback.**

Thank you for this super fast fix!

**Comment by Aekung** [comment]
I think you might now be debugging the plugin since the console shows error about duplicate Room and Location device is currently using. In this case, I will just quit testing for now to make sure that I'm not interfering your debugging process.

Please let me know when it's okay to test and I will jump in to try out =)

Thank you very much.

**Comment by hirakujira** [comment]
Ahh, sorry didn't see the updated message. Does it work now? Because I tested it and it works. Now I deleted your config in my config.json so you can change password if it works.

**Comment by Aekung** [comment]
This is the latest error I've got. The error is not the same now.

```
Jan 26 16:11:03 raspberrypi homebridge[4385]: {
Jan 26 16:11:03 raspberrypi homebridge[4385]:   reason: 'Duplicate devices having the location_name/room_name combination'
Jan 26 16:11:03 raspberrypi homebridge[4385]: }
Jan 26 16:11:03 raspberrypi homebridge[4385]: {
Jan 26 16:11:03 raspberrypi homebridge[4385]:   reason: 'Duplicate devices having the location_name/room_name combination'
Jan 26 16:11:03 raspberrypi homebridge[4385]: }
Jan 26 16:11:03 raspberrypi homebridge[4385]: [26/01/2021, 16:11:03] Got SIGTERM, shutting down Homebridge...
```

Note that I only add 1 device in, not 2 at the same time. I am now only running your plugin. I uninstalled the ambi climate plugin already. Not really sure why it's reporting duplicate devices having the same name. 

Note that this error comes when trying to turn off the air conditioner switch.

**Comment by hirakujira** [comment]
This is my config that I tested for your account. Could you try whether this works?

```
{
        "platform": "AmbiClimatePlatform",
        "clientId": "8c251f40-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "clientSecret": "acb328de-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "username": "ae.xxxxx@gmail.com",
        "password": "xxxxxxxxxxxxx",
        "accessories": [
            {
                "roomName": "Bedroom",
                "locationName": "Home"
            },
            {
                "roomName": "Home-Theater",
                "locationName": "Home"
            }
        ]
    }
```

**Comment by Aekung** [comment]
It works until I pressed on turning off the air conditioner switch. Doing so will then crashing homebridge with "reason: 'Duplicate devices having the location_name/room_name combination'".

Also, if trying to enable HeaterCooler Mode, homebridge would crash immediately.

**Comment by hirakujira** [comment]
Updated to v1.1.1. Fixed the issues you mentioned. Thanks!

**Comment by Aekung** [comment]
Thanks. The On/Off is now working correctly.

However, the HeaterCooler Mode is still throwing the same error as On/Off previously did when trying to switch the HeaterCooler Mode

```
Jan 26 16:43:50 raspberrypi homebridge[8130]: {
Jan 26 16:43:50 raspberrypi homebridge[8130]:   reason: 'Duplicate devices having the location_name/room_name combination'
Jan 26 16:43:50 raspberrypi homebridge[8130]: }
Jan 26 16:43:50 raspberrypi homebridge[8130]: {
Jan 26 16:43:50 raspberrypi homebridge[8130]:   reason: 'Duplicate devices having the location_name/room_name combination
```
Do you think it might be the same issue that happened to On/Off previously?

**Comment by hirakujira** [comment]
Yes. Sorry my bad. Now it's fixed too

**Comment by Aekung** [comment]
Wow! Everything is now working correctly and working very good as well. 

Thank you very much for the fix, Hiraku!

I will change the password back now. You are awesome!

**Comment by hirakujira** [comment]
Thanks for your patience and help. Wish you have a nice day!
