### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Unhandled promise rejection. 

### ISSUE THREAD

**Issue by keiranlovett** [hirakujira/homebridge-ambiclimate-platform#7]
**Describe The Bug:**

Seems to be a repeat of #5, I am not sure if this is a user configuration error or a bug. I have created and supplied the authorization details as instructed.

```
 UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1289)
(node:1637) UnhandledPromiseRejectionWarning: ReferenceError: nil is not defined
    at /homebridge/node_modules/homebridge-ambiclimate-platform/node_modules/node-ambiclimate/ambi-auth.js:135:9
```

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by rn1604** [comment]
Same here:

(node:677) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 145)

**Comment by hirakujira** [comment]
Cloud you try latest version and check whether it's fixed?

**Comment by keiranlovett** [comment]
No change....
