### ISSUE TITLE
Keep getting "Get current relative humidity failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}" error

### ISSUE THREAD

**Issue by stonecan** [hirakujira/homebridge-ambiclimate-platform#9]
**Describe The Bug:**
After a simple clean install with only one plugin on HomeBridge and fresh Ambi Labs OAuth setup with just one AmbiClimate 2 device, I keep getting these errors directly after restarting HomeBridge:

```
[AmbiClimatePlatform] Get current relative humidity failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[AmbiClimatePlatform] Get current tempature failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}

```
**To Reproduce:**
Only basic installation and restarting HomeBridge already creates this error.

**Expected behavior:**
Working connection to AmbiClimate device.

**Logs:**

Errors shown above already.

**Plugin Config:**

```
{
    "clientId": "c97xxxxxx",
    "clientSecret": "291xxxxxx",
    "username": "jxxxx@gmail.com",
    "password": "xxxxx",
    "showFeedbacks": true,
    "heaterCoolerMode": false,
    "accessories": [
        {
            "roomName": "Living Room",
            "locationName": "HOME"
        }
    ],
    "platform": "AmbiClimatePlatform"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.6
* **Homebridge Version**: v1.3.8
* **Node.js Version**: v14.18.1
* **NPM Version**: v6.14.15
* **Operating System**:  Docker (Ubuntu)

**Comment by hirakujira** [comment]
It still works for me. Maybe you need to check whether your clientId and clientSecret are valid?

To check them, please follow this:

https://api.ambiclimate.com/doc/quickstart

And make sure that you can get the response from step 4. The response would like this:
```
{
    expires_in: 144000,
    scope: "email device_read ac_control",
    token_type: "Bearer",
    access_token: "tM88C..............",
    refresh_token: "Ymlnp.............."
}
```

If you can get a response as above, then your `clientId` and `clientSecret` are valid

**Comment by stonecan** [comment]
This was my thought as well, but I've been re-generating the OAuth Application multiple times and the error persists.

The AmbiLabs quickstart step 4 response is:

```
{
   "scope": "email device_read ac_control",
   "expires_in": 144000,
   "access_token": "GisfE2....................",
   "refresh_token": "Acu3OX....................",
   "token_type": "Bearer"
}
```

So everything seems ok on this side.

**Comment by hirakujira** [comment]
Could you try this: https://www.npmjs.com/package/homebridge-ambiclimate ?
Because I use the same way to auth the account as this package, if you can login with this one, then ... it should work with my package...
